### ISSUE TITLE
false domain

### ISSUE THREAD

**Issue by ZMJGMADHPXWT** [What-Zit-Tooya/Ad-Block#11]
Hi.
The line 1149 looks like "0.0.0.0 https://ynuf.aliapp.org/saveWb.json?"  and I think this is a mistake. 
! Last modified: 30 Nov 2021 04:45 PM UTC+7
! Version: 30/11/2021
If you can update this host-file, I'll appreciate that.

Thanks in advance.

**Comment by spirillen** [comment]
This repo is not maintained... Last change to any file in this repo was: `Nov 30, 2021`

If you like maintained blacklists with easy commit tool, I can offer you to use [mypdns.eu.org](https://mypdns.eu.org/) there are smart [add-ons](https://mypdns.eu.org/#matrix=tools/README.md) for your Firefox Browser

**Comment by ZMJGMADHPXWT** [comment]
Thanks, I'll take a look.
