### ISSUE TITLE
Invalid Domains

### ISSUE THREAD

**Issue by p1r473** [What-Zit-Tooya/Ad-Block#2]
Hi @What-Zit-Tooya 
3 domains have invalid characters

      - mini:com.opera.mini.native
      - com.whatsapp]
      - com.whatsapp.w4b]

**Comment by What-Zit-Tooya** [comment]
Thats not a domain, thats a Android ID package name.
If you search that on playstore you'll find these:
`https://play.google.com/store/apps/details?id=com.whatsapp`
`https://play.google.com/store/apps/details?id=com.whatsapp.w4b`
`https://play.google.com/store/apps/details?id=com.opera.mini.native`

**Comment by p1r473** [comment]
Sorry, you are correct
I recommend changing the commented lines to begin with # insteas of [ and ! so that scripts don't incorrectly parse these commented lines.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Sorry, you are correct
> I recommend changing the commented lines to begin with # insteas of [ and ! so that scripts don't incorrectly parse these commented lines.

Noted.
Thanks for recommend. :)
