### ISSUE TITLE
ipv4.scdnco.spotify.map.fastly.net

### ISSUE THREAD

**Issue by badmojr** [What-Zit-Tooya/Ad-Block#3]
Hello!

Does the domain above serve questionable content somewhere?
I've noticed 2 domains that resolve to that address through CNAMEs.
```
audio4-fa.scdn.co CNAME ipv4.scdnco.spotify.map.fastly.net
download.scdn.co CNAME scdnco.spotify.map.fastly.net
```

10X.

**Comment by What-Zit-Tooya** [comment]
Ahh... `spotify domain` those are very complicated.
1 domain can serve ads and normal music in same time.
Block `audio4-fa.scdn.co` can block audio ads, also it block normal music. `download.scdn.co` serve official download client.

My adblock pull `spotify` adblock from https://github.com/AlfonsoVergara-github/Host-to-block-ads-for-spotify 
And i need investigating through them.

**Comment by badmojr** [comment]
Cool! Thank you.

**Comment by What-Zit-Tooya** [comment]
https://github.com/What-Zit-Tooya/Ad-Block/commit/93feef64439f8c2de79cc881e6151b522c854f99
