### ISSUE TITLE
Broken record...

### ISSUE THREAD

**Issue by spirillen** [What-Zit-Tooya/Ad-Block#6]
There is a breakage in this line....

https://github.com/What-Zit-Tooya/Ad-Block/blob/094105e30e82f13127e63f0575b8bcdb4e055a20/Additional-Blocklist/Spotify/Spotify-Blocklist-HOSTS.txt#L118

**Comment by What-Zit-Tooya** [comment]
Fixed https://github.com/What-Zit-Tooya/Ad-Block/commit/1792d5ffb3300f13c9e82229ba2bd39095019c79
